from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill


OUTPUT_PATH = Path(r"e:\Data\Desktop\Work On\extraction_method_literature_20plus.xlsx")
INVALID_SHEET_TITLE_CHARS = set(r"[]:*?/\\")


HEADERS = [
    "类别",
    "优先级",
    "文献标题",
    "DOI",
    "年份",
    "文献类型",
    "对象/体系",
    "脱矿试剂",
    "还原剂/巯基乙醇",
    "裂解液/提取体系",
    "胍盐/尿素/SDS 等强变性剂",
    "方法关键词",
    "主要内容/可借鉴点",
    "与 EDTA + IP 裂解液方法的关系",
    "备注/需回原文核对点",
]


ROWS = [
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Extraction and quantification by ELISA of eggshell organic matrix proteins (ovocleidin-17, ovalbumin, ovotransferrin) in shell from young and old hens",
        "DOI": "10.1093/ps/79.4.580",
        "年份": 2000,
        "文献类型": "期刊论文/提取定量方法",
        "对象/体系": "鸡蛋壳有机基质蛋白",
        "脱矿试剂": "20% 乙酸",
        "还原剂/巯基乙醇": "未说明",
        "裂解液/提取体系": "酸脱矿释放基质；ELISA 定量",
        "胍盐/尿素/SDS 等强变性剂": "未说明/未作为核心体系",
        "方法关键词": "acetic acid demineralization; eggshell organic matrix; ELISA",
        "主要内容/可借鉴点": "从蛋壳中提取并定量 OC-17、ovalbumin、ovotransferrin 等有机基质蛋白，是蛋壳酸脱矿提取的经典参照。",
        "与 EDTA + IP 裂解液方法的关系": "可作为酸法对照，比较乙酸脱矿与 EDTA 温和脱矿对蛋白回收和构象/PTM 保留的差异。",
        "备注/需回原文核对点": "需核对乙酸处理时间、温度、后续中和/冻干步骤。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Proteomic analysis of the acid-soluble organic matrix of the chicken calcified eggshell layer",
        "DOI": "10.1002/pmic.200600120",
        "年份": 2006,
        "文献类型": "期刊论文/蛋白组学方法",
        "对象/体系": "鸡蛋壳钙化层酸溶性有机基质",
        "脱矿试剂": "酸溶体系；具体酸种和浓度需回原文",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "acid-soluble organic matrix extraction",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "acid-soluble matrix; eggshell proteomics; LC-MS/MS",
        "主要内容/可借鉴点": "对鸡蛋壳钙化层酸溶性基质做蛋白组分析，提供传统酸溶提取后可鉴定蛋白谱。",
        "与 EDTA + IP 裂解液方法的关系": "可作为传统酸溶蛋白组学路线对照，突出 EDTA + IP 对非酸溶/弱相互作用蛋白的潜在保留。",
        "备注/需回原文核对点": "需核对酸提、酶解、质谱前处理细节。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Phosphoproteins of the chicken eggshell calcified layer",
        "DOI": "10.1002/pmic.200600635",
        "年份": 2007,
        "文献类型": "期刊论文/PTM 蛋白组学",
        "对象/体系": "鸡蛋壳钙化层磷蛋白/磷肽",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "蛋壳基质蛋白提取后磷肽富集",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "phosphoproteomics; phosphopeptide enrichment; eggshell calcified layer",
        "主要内容/可借鉴点": "鉴定蛋壳钙化层磷蛋白和磷酸化位点，说明提取和富集流程对 PTM 检出很关键。",
        "与 EDTA + IP 裂解液方法的关系": "可支持后续用 PTM 保留率和磷酸化谱完整性评价新提取方法。",
        "备注/需回原文核对点": "需核对磷肽富集材料、去盐和酶切方案。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Proteins of insoluble matrix of avian (Gallus gallus) eggshell",
        "DOI": "10.1080/03008200601003116",
        "年份": 2007,
        "文献类型": "期刊论文/不溶基质蛋白",
        "对象/体系": "鸡蛋壳不溶性基质蛋白",
        "脱矿试剂": "EDTA 相关不溶组分；需核对浓度",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "EDTA-insoluble matrix enzymatic digestion",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "EDTA-insoluble matrix; avian eggshell; HPLC-MS",
        "主要内容/可借鉴点": "针对 EDTA 脱矿后残留的不溶基质做酶切和质谱鉴定，补足酸溶基质之外的蛋白群。",
        "与 EDTA + IP 裂解液方法的关系": "与你的方法最贴近，可比较 IP 裂解液是否能提高 EDTA 后不溶/弱溶组分释放。",
        "备注/需回原文核对点": "需核对 EDTA pH、脱矿时长和酶切前处理。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Determination of insoluble avian eggshell matrix proteins",
        "DOI": "10.1007/s00216-009-3326-3",
        "年份": 2010,
        "文献类型": "期刊论文/分析方法",
        "对象/体系": "鸟类蛋壳不溶性基质蛋白",
        "脱矿试剂": "EDTA 相关不溶组分；需核对浓度",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "不溶基质蛋白测定流程",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "insoluble eggshell matrix; analytical determination; proteomics",
        "主要内容/可借鉴点": "提供不溶性蛋壳基质蛋白的测定方法，可用于设计新方法后的验证指标。",
        "与 EDTA + IP 裂解液方法的关系": "适合用作不溶组分检测和回收率比较的参考。",
        "备注/需回原文核对点": "需核对样本洗涤、消化、质谱方法。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "重点精读",
        "文献标题": "Isolation of ovocleidin-116 from chicken eggshells: microsequence analysis, isolation, and cleavage of the dermatan sulfate proteoglycan avian eggshell matrix protein",
        "DOI": "10.1016/S0945-053X(02)00031-8",
        "年份": 2002,
        "文献类型": "期刊论文/单蛋白分离",
        "对象/体系": "鸡蛋壳 OC-116/蛋白聚糖相关基质蛋白",
        "脱矿试剂": "可溶性蛋壳基质路线；具体需回原文",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "soluble eggshell matrix + chromatographic fractionation",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "ovocleidin-116; proteoglycan; chromatography; glycosylation",
        "主要内容/可借鉴点": "分离 OC-116 并分析二硫键、糖基化 Asn 和蛋白片段，对结构/PTM 保留讨论有价值。",
        "与 EDTA + IP 裂解液方法的关系": "可作为证明新方法是否保留蛋白聚糖/糖基化相关信息的参照。",
        "备注/需回原文核对点": "需核对层析缓冲液和是否存在还原/烷基化步骤。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Purification and immunochemistry of a soluble matrix protein of the chicken eggshell (ovocleidin 17)",
        "DOI": "10.1007/BF00298593",
        "年份": 1995,
        "文献类型": "期刊论文/单蛋白纯化",
        "对象/体系": "鸡蛋壳 OC-17 可溶性基质蛋白",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "soluble matrix purification",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "OC-17; soluble matrix protein; purification; immunochemistry",
        "主要内容/可借鉴点": "早期从蛋壳可溶基质中纯化 OC-17，是单蛋白功能和抗体检测的基础文献。",
        "与 EDTA + IP 裂解液方法的关系": "可作为单蛋白回收和免疫学验证的候选参照。",
        "备注/需回原文核对点": "需核对纯化步骤和缓冲液。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Extraction of glycosaminoglycans from chicken eggshell",
        "DOI": "10.1093/ps/80.5.681",
        "年份": 2001,
        "文献类型": "期刊论文/GAG 提取",
        "对象/体系": "鸡蛋壳糖胺聚糖",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "不适用/需回原文核对",
        "裂解液/提取体系": "GAG extraction workflow",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "glycosaminoglycan; eggshell; proteoglycan-associated matrix",
        "主要内容/可借鉴点": "说明蛋壳基质不只是蛋白，也包含 GAG/蛋白聚糖相关成分，提取方法可能影响复合体保留。",
        "与 EDTA + IP 裂解液方法的关系": "可支持后续检测糖基化/蛋白聚糖相关组分，避免只看总蛋白量。",
        "备注/需回原文核对点": "需核对蛋白酶消化和多糖回收步骤。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Solubilization and identification of hen eggshell membrane proteins during different times of chicken embryo development using the proteomic approach",
        "DOI": "10.1007/s10930-013-9487-0",
        "年份": 2013,
        "文献类型": "期刊论文/膜蛋白增溶",
        "对象/体系": "鸡蛋壳膜蛋白",
        "脱矿试剂": "不以脱矿为核心；需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "solubilization + proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "eggshell membrane; solubilization; proteomics",
        "主要内容/可借鉴点": "处理壳膜这类难溶蛋白网络，对你设计 IP 裂解液增溶验证有启发。",
        "与 EDTA + IP 裂解液方法的关系": "可作为壳膜/不溶蛋白增溶方法的补充对照。",
        "备注/需回原文核对点": "需核对是否使用 SDS、尿素、DTT 或巯基乙醇。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Proteomic analysis provides new insight into the eggshell cuticle",
        "DOI": "10.1016/j.jprot.2012.03.019",
        "年份": 2012,
        "文献类型": "期刊论文/蛋白组学",
        "对象/体系": "蛋壳角质层",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "cuticle protein extraction + proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "eggshell cuticle; proteomics; layer-specific extraction",
        "主要内容/可借鉴点": "角质层蛋白组学，为分层提取和表层污染/层级差异控制提供参考。",
        "与 EDTA + IP 裂解液方法的关系": "可帮助设计 mineralized layer 与 cuticle 分层对照。",
        "备注/需回原文核对点": "需核对采样层位和洗涤步骤。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Novel identification of matrix proteins involved in calcitic biomineralization",
        "DOI": "10.1016/j.jprot.2015.01.002",
        "年份": 2015,
        "文献类型": "期刊论文/矿化相关蛋白组学",
        "对象/体系": "方解石生物矿化相关基质蛋白",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "matrix protein extraction + proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "calcitic biomineralization; matrix proteins; proteomics",
        "主要内容/可借鉴点": "将提取到的基质蛋白和方解石矿化过程联系起来，适合用于功能相关讨论。",
        "与 EDTA + IP 裂解液方法的关系": "可为后续矿化实验选择候选蛋白或功能 readout 提供依据。",
        "备注/需回原文核对点": "需核对样本来源和提取条件。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Quantitative proteomics and bioinformatics analysis provide new insight into protein function during avian eggshell biomineralization",
        "DOI": "10.1016/j.jprot.2014.09.024",
        "年份": 2015,
        "文献类型": "期刊论文/定量蛋白组学",
        "对象/体系": "鸟类蛋壳生物矿化阶段相关蛋白",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "matrix protein extraction + quantitative proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "quantitative proteomics; avian eggshell; biomineralization",
        "主要内容/可借鉴点": "用定量蛋白组学解析蛋壳矿化相关蛋白功能，适合用于你后续多组学结果解释。",
        "与 EDTA + IP 裂解液方法的关系": "可比较新方法是否提高功能相关蛋白覆盖度。",
        "备注/需回原文核对点": "需核对定量策略和提取缓冲液。",
    },
    {
        "类别": "蛋壳基质/蛋壳膜",
        "优先级": "普通参考",
        "文献标题": "Quantitative proteomics provides new insights into chicken eggshell matrix protein functions during the primary events of mineralization and the active calcification phase",
        "DOI": "10.1016/j.jprot.2015.05.034",
        "年份": 2015,
        "文献类型": "期刊论文/定量蛋白组学",
        "对象/体系": "鸡蛋壳矿化早期与活跃钙化阶段基质蛋白",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "matrix protein extraction + quantitative proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "active calcification; mineralization stage; eggshell matrix proteomics",
        "主要内容/可借鉴点": "比较矿化早期和活跃钙化期的蛋壳基质蛋白，适合支撑阶段性功能解释。",
        "与 EDTA + IP 裂解液方法的关系": "可作为新方法评价中“功能相关蛋白是否更完整”的参照。",
        "备注/需回原文核对点": "需核对样本分期和提取流程。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "重点精读",
        "文献标题": "Dissociative extraction and reconstitution of extracellular matrix components involved in local bone differentiation",
        "DOI": "10.1073/pnas.78.12.7599",
        "年份": 1981,
        "文献类型": "期刊论文/经典骨基质提取与重构",
        "对象/体系": "脱矿骨基质中的骨诱导 ECM 组分",
        "脱矿试剂": "demineralized bone matrix；脱矿制备细节需回原文",
        "还原剂/巯基乙醇": "未作为核心信息",
        "裂解液/提取体系": "dissociative extraction + reconstitution",
        "胍盐/尿素/SDS 等强变性剂": "4 M guanidine-HCl; 8 M urea/1 M NaCl; 1% SDS",
        "方法关键词": "demineralized bone matrix; guanidine-HCl; urea; SDS; reconstitution",
        "主要内容/可借鉴点": "比较 4 M GdnHCl、8 M urea/1 M NaCl、1% SDS 对骨诱导活性的提取和重构效果，是矿化 ECM 强解离提取的经典。",
        "与 EDTA + IP 裂解液方法的关系": "提供强变性/强解离路线对照，可凸显你的 EDTA + IP 更温和、更适合构象/PTM 讨论。",
        "备注/需回原文核对点": "可重点看活性恢复 bioassay 和重构逻辑。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "重点精读",
        "文献标题": "Distribution of bone inductive proteins in mineralized and demineralized extracellular matrix",
        "DOI": "10.1016/0006-291X(84)90865-9",
        "年份": 1984,
        "文献类型": "期刊论文/骨基质分布与提取",
        "对象/体系": "矿化与脱矿骨 ECM 中的骨诱导蛋白",
        "脱矿试剂": "EDTA 相关脱矿；需核对浓度",
        "还原剂/巯基乙醇": "未说明",
        "裂解液/提取体系": "顺序提取",
        "胍盐/尿素/SDS 等强变性剂": "guanidine-HCl",
        "方法关键词": "mineralized matrix; demineralized matrix; bone inductive protein; sequential extraction",
        "主要内容/可借鉴点": "讨论骨诱导蛋白在矿化与脱矿 ECM 中的分布，对理解脱矿步骤导致的蛋白释放/保留很重要。",
        "与 EDTA + IP 裂解液方法的关系": "可帮助写“脱矿不只是去矿物，也改变蛋白可提取性”的理论依据。",
        "备注/需回原文核对点": "建议核对 GdnHCl 与 EDTA 的先后顺序。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "重点精读",
        "文献标题": "Method Development of Efficient Protein Extraction in Bone Tissue for Proteome Analysis",
        "DOI": "10.1021/pr070056t",
        "年份": 2007,
        "文献类型": "期刊论文/骨组织蛋白组提取方法",
        "对象/体系": "骨组织总蛋白和非胶原蛋白",
        "脱矿试剂": "HCl; EDTA",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "bone protein extraction for proteomics",
        "胍盐/尿素/SDS 等强变性剂": "guanidine-HCl; 可能涉及尿素/蛋白组学缓冲液，需核对",
        "方法关键词": "bone tissue; efficient protein extraction; proteome analysis; HCl; EDTA; guanidine-HCl",
        "主要内容/可借鉴点": "专门优化骨组织蛋白提取以适配蛋白组学，是矿化组织蛋白提取方法比较的核心文献。",
        "与 EDTA + IP 裂解液方法的关系": "最适合用来建立你的方法比较框架：提取效率、质谱兼容性、非胶原蛋白覆盖度。",
        "备注/需回原文核对点": "需核对各方案蛋白回收量和 MS 鉴定数。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "重点精读",
        "文献标题": "Empirical Evaluation of Bone Extraction Protocols",
        "DOI": "10.1371/journal.pone.0031443",
        "年份": 2012,
        "文献类型": "期刊论文/方案比较",
        "对象/体系": "现代骨和古骨蛋白提取",
        "脱矿试剂": "HCl; EDTA",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "骨蛋白提取方案比较",
        "胍盐/尿素/SDS 等强变性剂": "guanidine-HCl; ammonium bicarbonate; SDS; urea/thiourea",
        "方法关键词": "bone extraction protocol; HCl; EDTA; GuHCl; SDS; urea; LC-MS compatibility",
        "主要内容/可借鉴点": "系统评价骨提取方案，特别适合拿来支撑‘不同脱矿剂和溶出体系会影响蛋白回收、纯度和质谱兼容性’。",
        "与 EDTA + IP 裂解液方法的关系": "可作为你论文中方法学比较的骨基质代表文献。",
        "备注/需回原文核对点": "注意其结论与现代样本/古样本差异。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "普通参考",
        "文献标题": "Biochemical Characterization of Major Bone-Matrix Proteins Using Nanoscale-Size Bone Samples and Proteomics Methodology",
        "DOI": "10.1074/mcp.M110.006718",
        "年份": 2011,
        "文献类型": "期刊论文/小样本骨基质蛋白组学",
        "对象/体系": "纳米级骨样本中的主要骨基质蛋白",
        "脱矿试剂": "需回原文核对",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "proteomics methodology for nanoscale bone samples",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "bone matrix proteins; nanoscale samples; proteomics",
        "主要内容/可借鉴点": "证明小量矿化组织也可以进行主要基质蛋白生化表征和蛋白组学分析。",
        "与 EDTA + IP 裂解液方法的关系": "适合支持少量蛋壳样品提取后做 PTM/蛋白组学的可行性。",
        "备注/需回原文核对点": "需核对样本量、脱矿/酶解流程。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "普通参考",
        "文献标题": "Characteristics of a 28-kDa Collagenous Protein Extracted with Guanidine from EDTA-Demineralized Rabbit Alveolar Bone",
        "DOI": "10.2334/josnusd1959.35.258",
        "年份": 1993,
        "文献类型": "期刊论文/EDTA 脱矿后胍盐提取",
        "对象/体系": "兔牙槽骨 EDTA 脱矿基质",
        "脱矿试剂": "EDTA",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "EDTA-demineralized bone + guanidine extraction",
        "胍盐/尿素/SDS 等强变性剂": "guanidine",
        "方法关键词": "EDTA-demineralized bone; guanidine extraction; collagenous protein",
        "主要内容/可借鉴点": "展示 EDTA 脱矿后再用胍盐提取特定胶原样蛋白的路线。",
        "与 EDTA + IP 裂解液方法的关系": "可作为 EDTA 后强胍盐提取对照，比较 IP 裂解液是否更温和。",
        "备注/需回原文核对点": "需核对 EDTA 浓度、GdnHCl 浓度和蛋白鉴定方式。",
    },
    {
        "类别": "骨/矿化组织",
        "优先级": "普通参考",
        "文献标题": "Alkali-Urea Extraction of Demineralized Bone Matrix Removes Noggin, an Inhibitor of Bone Morphogenetic Proteins",
        "DOI": "10.1080/03008200490903048",
        "年份": 2004,
        "文献类型": "期刊论文/DBM 处理方法",
        "对象/体系": "脱矿骨基质中的 BMP 调控因子",
        "脱矿试剂": "demineralized bone matrix；具体需回原文",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "alkali-urea extraction",
        "胍盐/尿素/SDS 等强变性剂": "urea",
        "方法关键词": "alkali-urea; demineralized bone matrix; Noggin; BMP",
        "主要内容/可借鉴点": "说明处理方式会选择性移除 BMP 抑制因子 Noggin，提示提取条件会改变功能相关蛋白组成。",
        "与 EDTA + IP 裂解液方法的关系": "可支撑你不应只看总蛋白量，还要看功能相关蛋白/抑制因子是否被保留。",
        "备注/需回原文核对点": "需核对碱/尿素浓度和活性测定。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "重点精读",
        "文献标题": "Enrichment of extracellular matrix proteins from tissues and digestion into peptides for mass spectrometry analysis",
        "DOI": "10.3791/53057",
        "年份": 2015,
        "文献类型": "JoVE 方法论文",
        "对象/体系": "组织 ECM 蛋白富集",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "分级去除细胞组分并富集 ECM",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "ECM enrichment; decellularization-like fractionation; mass spectrometry",
        "主要内容/可借鉴点": "经典 ECM 富集与质谱前处理方法，可用于设计蛋壳基质中非目标污染蛋白去除策略。",
        "与 EDTA + IP 裂解液方法的关系": "可借鉴其分级提取思想，证明你的方法不仅高效，还能保留 matrix-enriched fraction。",
        "备注/需回原文核对点": "需核对各级提取缓冲液、去污剂和酶解方案。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "重点精读",
        "文献标题": "Characterization of the extracellular matrix of normal and diseased tissues using proteomics",
        "DOI": "10.1021/acs.jproteome.7b00191",
        "年份": 2017,
        "文献类型": "期刊论文/ECM 蛋白组方法",
        "对象/体系": "正常和疾病组织 ECM",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "ECM enrichment + proteomics",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "matrisome; ECM proteomics; tissue fractionation",
        "主要内容/可借鉴点": "提供用蛋白组学表征 ECM 的成熟框架，可用于后续定义蛋壳 matrix protein set。",
        "与 EDTA + IP 裂解液方法的关系": "可作为评价提取物 matrix-enrichment 程度的理论和数据库支持。",
        "备注/需回原文核对点": "可结合 MatrisomeDB 做蛋白分类。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "普通参考",
        "文献标题": "The matrisome: in silico definition and in vivo characterization by proteomics of normal and tumor extracellular matrices",
        "DOI": "10.1074/mcp.M111.014647",
        "年份": 2012,
        "文献类型": "期刊论文/ECM 定义与蛋白组学",
        "对象/体系": "正常和肿瘤 ECM/matrisome",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "ECM proteomics workflow",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "matrisome; ECM definition; proteomics",
        "主要内容/可借鉴点": "定义 matrisome 并用蛋白组学验证，是 ECM 蛋白分类的重要基础。",
        "与 EDTA + IP 裂解液方法的关系": "可用于给蛋壳提取蛋白做 matrix-associated 分组和功能注释。",
        "备注/需回原文核对点": "不是提取 protocol，但适合作为分类依据。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "普通参考",
        "文献标题": "The extracellular matrix: tools and insights for the omics era",
        "DOI": "10.1016/j.matbio.2015.06.003",
        "年份": 2016,
        "文献类型": "综述/方法框架",
        "对象/体系": "ECM 组学研究",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "不适用/需按具体方法",
        "裂解液/提取体系": "ECM omics tools overview",
        "胍盐/尿素/SDS 等强变性剂": "按具体方法",
        "方法关键词": "ECM omics; matrisome; proteomics tools",
        "主要内容/可借鉴点": "综述 ECM 组学工具和挑战，适合引言中说明基质蛋白提取难点。",
        "与 EDTA + IP 裂解液方法的关系": "可帮助论证蛋壳基质蛋白属于难提取 ECM-like/mineral-associated system。",
        "备注/需回原文核对点": "作为背景文献，不作为 SOP。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "普通参考",
        "文献标题": "Defining the extracellular matrix using proteomics",
        "DOI": "10.1111/iep.12011",
        "年份": 2013,
        "文献类型": "综述/方法视角",
        "对象/体系": "ECM 蛋白组学",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "不适用/需按具体方法",
        "裂解液/提取体系": "proteomics-based ECM definition",
        "胍盐/尿素/SDS 等强变性剂": "按具体方法",
        "方法关键词": "ECM definition; proteomics; matrix enrichment",
        "主要内容/可借鉴点": "讨论用蛋白组学定义 ECM 的技术问题，适合支撑提取后如何解释蛋白列表。",
        "与 EDTA + IP 裂解液方法的关系": "可为提取物中 matrix protein、associated protein、contaminant 的分类提供思路。",
        "备注/需回原文核对点": "作为方法学背景引用。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "普通参考",
        "文献标题": "Quantification of extracellular matrix proteins from a rat lung scaffold to provide a molecular readout for tissue engineering",
        "DOI": "10.1074/mcp.M114.045260",
        "年份": 2015,
        "文献类型": "期刊论文/ECM 定量蛋白组学",
        "对象/体系": "大鼠肺支架 ECM",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "ECM protein quantification workflow",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "ECM quantification; tissue scaffold; molecular readout",
        "主要内容/可借鉴点": "用定量蛋白组学评价支架 ECM 组成，可借鉴为蛋壳提取物质量评价指标。",
        "与 EDTA + IP 裂解液方法的关系": "可支持你设计“蛋白总量 + matrix protein coverage + PTM”多指标评价。",
        "备注/需回原文核对点": "需核对定量策略。",
    },
    {
        "类别": "ECM/组织基质富集",
        "优先级": "普通参考",
        "文献标题": "Proteomic definitions of basement membrane composition in health and disease",
        "DOI": "10.1016/j.matbio.2016.08.006",
        "年份": 2017,
        "文献类型": "综述/蛋白组学定义",
        "对象/体系": "基底膜 ECM",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "不适用/需按具体方法",
        "裂解液/提取体系": "basement membrane proteomics",
        "胍盐/尿素/SDS 等强变性剂": "按具体方法",
        "方法关键词": "basement membrane; ECM proteomics; composition",
        "主要内容/可借鉴点": "强调 ECM 组成定义和疾病/状态差异，可借鉴于蛋壳不同结构层对比。",
        "与 EDTA + IP 裂解液方法的关系": "可帮助构建提取物组成谱而非单一效率的评价思路。",
        "备注/需回原文核对点": "背景文献。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "重点精读",
        "文献标题": "Universal sample preparation method for proteome analysis",
        "DOI": "10.1038/nmeth.1322",
        "年份": 2009,
        "文献类型": "Nature Methods/样品制备方法",
        "对象/体系": "复杂蛋白样本的质谱前处理",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "按 FASP 流程；需回原文核对",
        "裂解液/提取体系": "FASP; detergent-compatible cleanup and digestion",
        "胍盐/尿素/SDS 等强变性剂": "SDS/尿素相关兼容处理",
        "方法关键词": "FASP; universal sample preparation; proteomics",
        "主要内容/可借鉴点": "解决去污剂和复杂裂解液样本进入质谱的问题，是 IP/RIPA/SDS 类裂解液后处理的经典。",
        "与 EDTA + IP 裂解液方法的关系": "如果 IP 裂解液影响质谱，这篇可作为后处理和酶解兼容方案。",
        "备注/需回原文核对点": "需核对滤膜、尿素浓度、洗涤步骤。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Quantitative evaluation of filter aided sample preparation (FASP) and multienzyme digestion FASP protocols",
        "DOI": "10.1021/acs.analchem.6b00859",
        "年份": 2016,
        "文献类型": "期刊论文/样品制备评价",
        "对象/体系": "FASP 与多酶消化方法",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "FASP and multienzyme FASP",
        "胍盐/尿素/SDS 等强变性剂": "尿素/SDS 兼容处理",
        "方法关键词": "FASP; multienzyme digestion; quantitative evaluation",
        "主要内容/可借鉴点": "量化比较 FASP 和多酶 FASP 的消化效果，适合优化蛋壳基质质谱前处理。",
        "与 EDTA + IP 裂解液方法的关系": "为 IP 裂解液提取后如何稳定进入 LC-MS/MS 提供方法依据。",
        "备注/需回原文核对点": "需核对消化酶组合。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "重点精读",
        "文献标题": "Evaluation of protein extraction methods to improve meta-proteomics analysis of treated wastewater biofilms",
        "DOI": "10.1002/pmic.202300191",
        "年份": 2023,
        "文献类型": "期刊论文/提取方法比较",
        "对象/体系": "废水生物膜复杂基质样本",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "B-PER; RIPA; PreOmics; SDS; AllPrep; Urea",
        "胍盐/尿素/SDS 等强变性剂": "SDS; Urea",
        "方法关键词": "RIPA; SDS; urea; B-PER; PreOmics; metaproteomics",
        "主要内容/可借鉴点": "比较多种裂解/提取体系的蛋白产量和鉴定效果，RIPA、SDS、PreOmics 等结果对你的 IP 裂解液选择很有参考价值。",
        "与 EDTA + IP 裂解液方法的关系": "直接支撑用裂解液提高复杂基质蛋白回收的合理性，也提醒要同时评价产量和鉴定数。",
        "备注/需回原文核对点": "体系不是蛋壳，但方法比较逻辑很有用。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Improving soil protein extraction for metaproteome analysis and glomalin-related soil protein detection",
        "DOI": "10.1002/pmic.200900251",
        "年份": 2009,
        "文献类型": "期刊论文/复杂基质蛋白提取",
        "对象/体系": "土壤蛋白/球囊霉素相关蛋白",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "sequential citrate and SDS buffers; phenol extraction",
        "胍盐/尿素/SDS 等强变性剂": "SDS",
        "方法关键词": "soil protein extraction; sequential extraction; phenol; SDS",
        "主要内容/可借鉴点": "复杂颗粒基质需要顺序提取和纯化，适合类比蛋壳矿物/有机基质混杂体系。",
        "与 EDTA + IP 裂解液方法的关系": "可支撑设计顺序提取：EDTA 脱矿后再用 IP 裂解液释放结合蛋白。",
        "备注/需回原文核对点": "非矿化动物体系，作为方法学类比。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Gel-free proteomic identification of the Bacillus subtilis insoluble spore coat protein fraction",
        "DOI": "10.1002/pmic.201100003",
        "年份": 2011,
        "文献类型": "期刊论文/不溶蛋白组学",
        "对象/体系": "枯草芽孢杆菌不溶孢子衣蛋白",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "insoluble protein fraction preparation",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "insoluble protein fraction; gel-free proteomics; LC-MS/MS",
        "主要内容/可借鉴点": "证明难溶蛋白组分也可通过 gel-free LC-MS/MS 鉴定。",
        "与 EDTA + IP 裂解液方法的关系": "可为蛋壳不溶基质蛋白直接质谱鉴定提供类比依据。",
        "备注/需回原文核对点": "非蛋壳体系，作为不溶蛋白方法参考。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Purification and Proteomic Analysis of a Nuclear-Insoluble Protein Fraction",
        "DOI": "10.1007/978-1-59745-028-7_9",
        "年份": 2007,
        "文献类型": "方法章节",
        "对象/体系": "核不溶蛋白组分",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "nuclear-insoluble fraction purification",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "insoluble protein fraction; purification; proteomic analysis",
        "主要内容/可借鉴点": "提供不溶蛋白分级纯化和蛋白组学分析思路。",
        "与 EDTA + IP 裂解液方法的关系": "可借鉴其分级提取思想，设计蛋壳可溶/不溶组分比较。",
        "备注/需回原文核对点": "作为通用不溶蛋白章节参考。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Total Protein Extraction with TCA-Acetone",
        "DOI": "10.1385/1-59745-227-0:1",
        "年份": 2007,
        "文献类型": "方法章节",
        "对象/体系": "总蛋白沉淀/提取",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "TCA-acetone precipitation/extraction",
        "胍盐/尿素/SDS 等强变性剂": "不以强变性裂解为核心",
        "方法关键词": "TCA-acetone; protein precipitation; total protein extraction",
        "主要内容/可借鉴点": "经典蛋白沉淀和去杂质方法，可用于提取后纯化或去盐。",
        "与 EDTA + IP 裂解液方法的关系": "可作为 IP 裂解液提取后去污剂/盐去除的备选。",
        "备注/需回原文核对点": "需注意沉淀法可能降低某些低丰度/疏水蛋白回收。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Preparation and Extraction of Insoluble (Inclusion-Body) Proteins from Escherichia coli",
        "DOI": "10.1002/0471140864.ps0603s70",
        "年份": 2012,
        "文献类型": "Current Protocols 方法章节",
        "对象/体系": "大肠杆菌包涵体不溶蛋白",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "常见包涵体体系可能涉及还原剂；需回原文核对",
        "裂解液/提取体系": "inclusion body protein preparation/extraction",
        "胍盐/尿素/SDS 等强变性剂": "常见为尿素/胍盐；需回原文核对",
        "方法关键词": "insoluble protein; inclusion body; urea; guanidine",
        "主要内容/可借鉴点": "虽是细菌体系，但展示了不溶蛋白如何通过变性剂提取和复性。",
        "与 EDTA + IP 裂解液方法的关系": "可作为强变性不溶蛋白提取的远端对照，不建议直接类比天然构象。",
        "备注/需回原文核对点": "用于方法讨论，不宜作为蛋壳体系主证据。",
    },
    {
        "类别": "通用蛋白提取/不溶蛋白",
        "优先级": "普通参考",
        "文献标题": "Chloroform/Methanol Protein Extraction and In-solution Trypsin Digestion Protocol for Bottom-up Proteomics Analysis",
        "DOI": "10.21769/bioprotoc.5055",
        "年份": 2024,
        "文献类型": "Bio-Protocol 方法",
        "对象/体系": "bottom-up proteomics 样品前处理",
        "脱矿试剂": "不适用",
        "还原剂/巯基乙醇": "需回原文核对",
        "裂解液/提取体系": "chloroform/methanol extraction + in-solution digestion",
        "胍盐/尿素/SDS 等强变性剂": "需回原文核对",
        "方法关键词": "chloroform/methanol; protein extraction; trypsin digestion; bottom-up proteomics",
        "主要内容/可借鉴点": "适合处理含脂质/干扰物的样品，提供质谱前净化思路。",
        "与 EDTA + IP 裂解液方法的关系": "可作为 IP 裂解液提取后净化和酶解的备选方案。",
        "备注/需回原文核对点": "Bio-Protocol，可作为操作参考。",
    },
]


def write_sheet(worksheet, rows: list[dict[str, object]]) -> None:
    worksheet.append(HEADERS)
    for row in rows:
        worksheet.append([row[header] for header in HEADERS])

    worksheet.freeze_panes = "A2"
    worksheet.auto_filter.ref = worksheet.dimensions

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="4F6D7A")
    wrap_alignment = Alignment(vertical="top", wrap_text=True)

    for cell in worksheet[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = wrap_alignment

    for row in worksheet.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = wrap_alignment

    widths = {
        "A": 20,
        "B": 12,
        "C": 70,
        "D": 28,
        "E": 10,
        "F": 22,
        "G": 28,
        "H": 28,
        "I": 20,
        "J": 34,
        "K": 32,
        "L": 40,
        "M": 48,
        "N": 48,
        "O": 34,
    }
    for column, width in widths.items():
        worksheet.column_dimensions[column].width = width


def safe_sheet_title(title: str) -> str:
    cleaned = "".join("-" if char in INVALID_SHEET_TITLE_CHARS else char for char in title)
    return cleaned[:31]


def build_workbook() -> Workbook:
    workbook = Workbook()

    all_sheet = workbook.active
    all_sheet.title = "全部方法文献"
    write_sheet(all_sheet, ROWS)

    priority_rows = [row for row in ROWS if row["优先级"] == "重点精读"]
    priority_sheet = workbook.create_sheet("优先精读")
    write_sheet(priority_sheet, priority_rows)

    categories = []
    for row in ROWS:
        category = row["类别"]
        if category not in categories:
            categories.append(category)

    for category in categories:
        sheet = workbook.create_sheet(safe_sheet_title(category))
        category_rows = [row for row in ROWS if row["类别"] == category]
        write_sheet(sheet, category_rows)

    return workbook


def main() -> None:
    workbook = build_workbook()
    workbook.save(OUTPUT_PATH)
    print(f"Created: {OUTPUT_PATH}")
    print(f"Total rows: {len(ROWS)}")
    print(f"Priority rows: {sum(1 for row in ROWS if row['优先级'] == '重点精读')}")


if __name__ == "__main__":
    main()